# Arquitectura de Redes y Servicios
# FI-UNPSJB-PM
#
# Imagen para el desarrollo del servidor de node de envios
# Destinada para utilizar en el desarrollo del trabajo de laboratorio.
FROM node:alpine

# Establece el directorio de trabajo
WORKDIR /home/startup-rabbit

# Establece la variable de entorno para definir el prompt de la terminal
ENV PS1="[startup-rabbit:\W]\$ "

# Por defecto ejecuta el comando bash
CMD [ "bash" ]